name: Postman

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: cd hello-go && npm install

    - name: Run Frontdoor
      run: cd hello-go && go run main.go &
    
    - name: Test
      run: npm test
