name: Postman

on:
  pull_request:
    paths:
      - "frontdoor-go/**"
      - ".github/**"
    branches:
      - '*'
  push:
    branches:
      - '*'
    paths:
      - "frontdoor-go/**"
      - ".github/**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # - name: Run server
    #   run: |
    #     cd hello-go
    #     go run main.go &

    # - name: Check Server Readiness
    #   run: |
    #     cd hello-go
    #     make check-readiness

    # - name: Test
    #   run: |
    #     cd hello-go
    #     npm install
    #     npm test

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
